import React, { useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { createJobEventSource, fetchClips, fetchEpisode, generateClips } from "../api/client";
import type { ClipCandidate, JobStateResponse } from "../api/types";

const fmt = (n: number) => `${Math.floor(n / 60)}:${Math.floor(n % 60).toString().padStart(2, "0")}`;
const media = (episode: string, path: string) => `/api/media/${encodeURIComponent(episode)}/${path.split(/[\\/]/).map(encodeURIComponent).join("/")}`;
export const ClipsPage: React.FC = () => {
  const { id = "" } = useParams<{ id: string }>(); const queryClient = useQueryClient();
  const [part, setPart] = useState(""); const [job, setJob] = useState<JobStateResponse | null>(null); const [message, setMessage] = useState(""); const audioRef = useRef<HTMLAudioElement>(null); const playbackCleanupRef = useRef<(() => void) | null>(null);
  const { data: episode } = useQuery({ queryKey: ["episode", id], queryFn: () => fetchEpisode(id) });
  const activePart = part || episode?.parts_detail?.[0]?.stem || episode?.parts?.[0]?.replace(/\.[^/.]+$/, "") || "";
  const { data, isLoading, error } = useQuery({ queryKey: ["clips", id, activePart], queryFn: () => fetchClips(id, activePart), enabled: Boolean(activePart) });
  useEffect(() => { if (!job) return; const cleanup = createJobEventSource(job.id, (event) => { setMessage(event.message || event.event); if (["job_finished", "job_failed", "job_cancelled"].includes(event.event)) { queryClient.invalidateQueries({ queryKey: ["clips", id, activePart] }); setJob(null); } }); return cleanup; }, [job, id, activePart, queryClient]);
  async function generate(render: boolean) { try { setMessage(render ? "正在產生候選並渲染檔案..." : "正在產生候選..."); setJob(await generateClips(id, activePart, render)); } catch (e) { setMessage((e as Error).message); } }
  function play(candidate: ClipCandidate) { const audio = audioRef.current; if (!audio) return; playbackCleanupRef.current?.(); const source = media(id, `parts/${activePart}/${activePart}.clean.wav`); let stop: (() => void) | null = null; const start = () => { audio.currentTime = candidate.start; void audio.play(); const onTimeUpdate = () => { if (audio.currentTime >= candidate.end) { audio.pause(); stop?.(); } }; audio.addEventListener("timeupdate", onTimeUpdate); stop = () => audio.removeEventListener("timeupdate", onTimeUpdate); }; const onLoadedMetadata = () => { audio.removeEventListener("loadedmetadata", onLoadedMetadata); start(); }; if (audio.src !== new URL(source, window.location.href).href) { audio.addEventListener("loadedmetadata", onLoadedMetadata); audio.src = source; } else { start(); } playbackCleanupRef.current = () => { audio.removeEventListener("loadedmetadata", onLoadedMetadata); stop?.(); audio.pause(); }; }
  useEffect(() => () => { playbackCleanupRef.current?.(); }, []);
  const parts = useMemo(() => episode?.parts_detail?.map((p) => p.stem) || episode?.parts?.map((p) => p.replace(/\.[^/.]+$/, "")) || [], [episode]);
  return <div className="clips-page"><header className="page-header"><div><Link className="dense-btn" to={`/episodes/${id}`}>← 返回集數</Link><h1>短片候選 <span className="mono">/ CLIPS</span></h1></div><div className="clip-actions"><button className="dense-btn" onClick={() => generate(false)} disabled={Boolean(job)}>產生候選</button><button className="dense-btn primary" onClick={() => generate(true)} disabled={Boolean(job)}>產生並渲染</button></div></header><div className="clips-toolbar"><label>段落 <select className="dense-select" value={activePart} onChange={(e) => setPart(e.target.value)}>{parts.map((p) => <option key={p} value={p}>{p}</option>)}</select></label><span className="mono">{message || (data ? `${data.candidates.length} 個候選` : "尚未產生候選")}</span></div>{job && <div className="job-progress"><span className="status-dot blue" />工作執行中 · SSE live</div>}{isLoading && <div className="empty-box">載入候選中...</div>}{error && <div className="empty-box">尚無候選。請先執行「產生候選」。</div>}{!isLoading && !error && data && <div className="clips-table-wrap"><table className="clips-table"><thead><tr><th>RANK</th><th>WINDOW</th><th>DURATION</th><th>SCORE</th><th>EXCERPT</th><th>ACTIONS</th></tr></thead><tbody>{data.candidates.map((candidate, index) => <tr key={String(candidate.id)}><td className="mono">{String(index + 1).padStart(2, "0")}</td><td className="mono">{fmt(candidate.start)} → {fmt(candidate.end)}</td><td className="mono">{fmt(candidate.end - candidate.start)}</td><td className="mono" title={candidate.score_components ? Object.entries(candidate.score_components).map(([k, v]) => `${k}: ${v}`).join("\n") : ""}>{candidate.score.toFixed(2)}</td><td className="excerpt">{candidate.text}</td><td><div className="row-actions"><button className="dense-btn" onClick={() => play(candidate)}>▶ 播放</button>{candidate.rendered?.mp3 && <a className="dense-btn" href={candidate.rendered.mp3} download>MP3</a>}{candidate.rendered?.srt && <a className="dense-btn" href={candidate.rendered.srt} download>SRT</a>}</div></td></tr>)}</tbody></table></div>}<audio ref={audioRef} controls className="clip-audio" /></div>;
};
